GET http://127.0.0.1:8000/get?arr=[{"s1":{"r":1,"a":0,"v":0},"s2":{"r":0,"a":0,"v":1}},{"s1":{"r":1,"a":0,"v":0},"s2":{"r":0,"a":0,"v":1}},{"s1":{"r":1,"a":0,"v":0},"s2":{"r":1,"a":0,"v":0}},{"s1":{"r":1,"a":1,"v":0},"s2":{"r":1,"a":0,"v":0}},{"s1":{"r":0,"a":0,"v":1},"s2":{"r":1,"a":0,"v":0}},{"s1":{"r":0,"a":1,"v":0},"s2":{"r":1,"a":0,"v":0}}]